version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Warsaw
  open-pull-requests-limit: 2
  reviewers:
  - kszarek
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Warsaw
  open-pull-requests-limit: 2
