FROM golang:1.12.9-alpine
ENV GO111MODULE=on
ENV CGO_ENABLED=0

WORKDIR /usr/src/app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
CMD ["go", "test", "-cover", "-v", "./..."]
