// Code generated by MockGen. DO NOT EDIT.
// Source: ssm.go
//
// Generated by this command:
//
//	mockgen -source=ssm.go -destination=mock_ssm.go -package=ssm SSMClient
//

// Package ssm is a generated GoMock package.
package ssm
