service: treasury

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  memorySize: 128
  cfLogs: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:table/treasury-${opt:stage, self:provider.stage}"
  environment:
    DYNAMODB_TABLE: treasury-${opt:stage, self:provider.stage}


functions:
  read:
    handler: read.read
    events:
      - http:
          path: v1/secret
          method: get
          cors: true

  write:
    handler: write.write
    events:
      - http:
          path: v1/secret
          method: post
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: treasury-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: version
            AttributeType: N
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
