name: tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -v -cover ./...
