name: tests
permissions:
  contents: read

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -v -cover -race ./...

      - name: Run Go Vet
        run: go vet ./...
