name: Check Golang vulnerabilities using Snyk
# https://docs.snyk.io/integrations/snyk-ci-cd-integrations/github-actions-integration/snyk-golang-action

on: pull_request
# Workflows triggered by Dependabot on the "push" event run with read-only access.
# Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot,
# please ensure you are using the "pull_request" event for this workflow and avoid triggering
# on the "push" event for Dependabot branches.
# See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push
# for more information on how to configure these events

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
